npm i -g @angular/cli
npm i -g corepack
npm i -g directus
npm i -g eas-cli
npm i -g eas
npm i -g epic-react-modal
npm i -g expo-cli
npm i -g gulp
npm i -g knex
npm i -g node-gyp
npm i -g nopt
npm i -g npm-check-updates
npm i -g npm
npm i -g pnpm
npm i -g prettier
npm i -g sass-migrator
npm i -g semver
npm i -g serve
npm i -g yarn
