code --install-extension 42Crunch.vscode-openapi
code --install-extension adamhartford.vscode-base64
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension Angular.ng-template
code --install-extension anseki.vscode-color
code --install-extension Arjun.swagger-viewer
code --install-extension bajdzis.vscode-database
code --install-extension batisteo.vscode-django
code --install-extension bceskavich.theme-dracula-at-night
code --install-extension bringout.pdf-view
code --install-extension bungcip.better-toml
code --install-extension burkeholland.simple-react-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension ckolkman.vscode-postgres
code --install-extension clinyong.vscode-css-modules
code --install-extension cweijan.vscode-mysql-client2
code --install-extension cyrilletuzi.angular-schematics
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension DotJoshJohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension file-icons.file-icons
code --install-extension formulahendry.auto-rename-tag
code --install-extension foxundermoon.shell-format
code --install-extension fterrag.vscode-php-cs-fixer
code --install-extension GraphQL.vscode-graphql
code --install-extension Gruntfuggly.todo-tree
code --install-extension GulajavaMinistudio.mayukaithemevsc
code --install-extension HungVo.htext
code --install-extension iocave.monkey-patch
code --install-extension Janne252.fontawesome-autocomplete
code --install-extension jaspernorth.vscode-pigments
code --install-extension jock.svg
code --install-extension johnsoncodehk.volar
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension junstyle.php-cs-fixer
code --install-extension leodevbro.blockman
code --install-extension magicstack.MagicPython
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode.hexeditor
code --install-extension Natizyskunk.sftp
code --install-extension naumovs.color-highlight
code --install-extension octref.vetur
code --install-extension PKief.angular-component-extractor
code --install-extension Prisma.vscode-graphql
code --install-extension rangav.vscode-thunder-client
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension Shan.code-settings-sync
code --install-extension shufo.vscode-blade-formatter
code --install-extension steoates.autoimport
code --install-extension styled-components.vscode-styled-components
code --install-extension syler.sass-indented
code --install-extension teabyii.ayu
code --install-extension tristanremy.mirage
code --install-extension valentjn.vscode-ltex
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension Vtrois.gitmoji-vscode
code --install-extension wix.vscode-import-cost
code --install-extension yzhang.markdown-all-in-one
